version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis_service
    restart: unless-stopped

  fastapi_health:
    build: ./services/health
    container_name: fastapi_health
    ports:
      - "${FASTAPI_HEALTH_PORT}:80"
    restart: unless-stopped

  fastapi_slow:
    build: ./services/slow
    container_name: fastapi_slow
    ports:
      - "${FASTAPI_SLOW_PORT}:80"
    restart: unless-stopped
  zbx_agent_redis:
    image: zabbix/zabbix-agent:alpine-7.2-latest
    container_name: zbx_agent_redis
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      ZBX_HOSTNAME: redis-service
    restart: unless-stopped

  zbx_agent_health:
    image: zabbix/zabbix-agent:alpine-7.2-latest
    container_name: zbx_agent_health
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      ZBX_HOSTNAME: health-api
    restart: unless-stopped

  zbx_agent_slow:
    image: zabbix/zabbix-agent:alpine-7.2-latest
    container_name: zbx_agent_slow
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      ZBX_HOSTNAME: slow-api
    restart: unless-stopped
