version: '3.8'

services:
  zabbix_agent:
    build:
      context: ./zabbix-agent
      args:
        ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
        ZBX_HOSTNAME: ${ZBX_HOSTNAME}
    container_name: zabbix_agent
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      ZBX_HOSTNAME: ${ZBX_HOSTNAME}
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_sim
    restart: unless-stopped

  fastapi_health:
    build: ./services/health
    container_name: fastapi_health
    ports:
      - "${FASTAPI_HEALTH_PORT}:80"
    restart: unless-stopped

  fastapi_slow:
    build: ./services/slow
    container_name: fastapi_slow
    ports:
      - "${FASTAPI_SLOW_PORT}:80"
    restart: unless-stopped
